baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Things UtsavBalar does'
theme = 'hello-friend-ng'

[params]
homeSubtitle = "Welcome to the chaotic cosmos of the mind of Utsav Balar"
disableReadOtherPosts = false
enableSharingButtons = true
enableGlobalLanguageMenu = true
description = "Things UtsavBalar does"
keywords = "homepage, blog"
images = [""]

[[params.social]]
name = "twitter"
url  = "https://twitter.com/utsavthecunt"

[[params.social]]
name = "email"
url  = "mailto:utsavbalar1231@gmail.com"

[[params.social]]
name = "github"
url  = "https://github.com/utsavbalar1231"

[[params.social]]
name = "telegram"
url  = "https://t.me/utsavthecunt"

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[params.portrait]
path = "/img/logo.jpg"
alt = "Logo was supposed to be here"

[[menu.main]]
identifier = "blogs"
name       = "Blogs"
url        = "/posts"
