baseURL = 'http://utsavbalar.vercel.app/'
languageCode = 'en-us'
title = 'Things UtsavBalar does and likes'
theme = 'hello-friend-ng'
relativeURLs = true

[languages]
[languages.en]
title = "Things UtsavBalar does and likes"
keywords = ""
copyright = 'CC BY-NC 4.0'
readOtherPosts = "Read other posts"

footerLeft = "Made with &#10084;"
footerRight = "Theme by Djordje Atlialp"

[languages.en.params.logo]
logoMark = ">"
logoText = "UtsavBalar"
logoHomeLink = "/"

[params]
homeSubtitle = "Welcome to the chaotic cosmos of the mind of Utsav Balar"
disableReadOtherPosts = false
enableSharingButtons = true
description = "Things UtsavBalar does"
keywords = "homepage, blog"
images = [""]

[[params.social]]
name = "twitter"
url  = "https://twitter.com/utsavthecunt"

[[params.social]]
name = "email"
url  = "mailto:utsavbalar1231@gmail.com"

[[params.social]]
name = "github"
url  = "https://github.com/utsavbalar1231"

[[params.social]]
name = "telegram"
url  = "https://t.me/utsavthecunt"

[params.portrait]
path = "/img/logo.jpg"
alt = "Logo was supposed to be here"

[taxonomies]
category = "categories"
tag      = "tags"
series   = "series"

[menu]
[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about"

[[menu.main]]
identifier = "blogs"
name       = "Blogs"
url        = "/blogs"

[[menu.main]]
identifier = "quotes"
name       = "Quotes"
url        = "/quotes"
